name: Tests

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  changes:
    runs-on: ubuntu-latest
    # # Required permissions
    # permissions:
    #   pull-requests: read
    # # Set job outputs to values from filter step
    outputs:
      relevant_files: ${{ steps.filter.outputs.relevant_files }}
    steps:
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          relevant_files:
            - 'nanolayer/**'
            - 'tests/**'
            - '.github/workflows/run-tests.yaml'

  run-tests:
    needs: [changes]  
    if: ${{ (needs.changes.outputs.relevant_files == 'true') || (github.event_name	== 'workflow_dispatch') }}

    strategy:
      fail-fast: false
      matrix:
        config:
          - {
            subtest_dir: "tests/installers/apt"
          }
          - {
            subtest_dir: "tests/installers/apt_get"
          }
          - {
            subtest_dir: "tests/installers/aptitude"
          }
          - {
            subtest_dir: "tests/installers/gh_release"
          }


    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: "Install latest devcontainer CLI"
        run: npm install -g @devcontainers/cli

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: "Test docker platform"
        run: |
          DOCKER_DEFAULT_PLATFORM=linux/arm64 docker run -t ubuntu uname -a

      - name: "Set up Python 3.10"
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: "Install python dependencies"
        run: |
          python -m pip install --upgrade pip 
          python -m pip install --upgrade build setuptools wheel setuptools-scm
          pip install -r requirements.txt -r requirements-dev.txt
      - name: "Test with pytest"
        run: |
          python -m pytest -s -v ${{ matrix.config.subtest_dir }}